<?xml version="1.0" encoding="utf-8"?>
<robot name="sentry_lidar" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find sentry233333)/urdf/xacro/sentry2.xacro" />


    <xacro:property name="lidar_offset_x" value="0.00246" />
    <xacro:property name="lidar_offset_y" value="0.0002" />
    <xacro:property name="lidar_offset_z" value="0.47178" />

    <!-- lidar -->
    <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro" />
    <xacro:VLP-16 parent="base_link">
        <origin xyz="${lidar_offset_x} ${lidar_offset_y} ${lidar_offset_z}" rpy="0 0 0" />
    </xacro:VLP-16>

    <xacro:sentry_simple />


    <!-- IMU -->
    <xacro:include filename="$(find sentry233333)/sensors/imu.xacro" />
    <xacro:imu sensor_name="imu" parent_link="base_link">
        <origin rpy="0 0 0" xyz="${lidar_offset_x} ${lidar_offset_y} ${lidar_offset_z+0.1}" />
    </xacro:imu>


    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/sentry_lidar</robotNamespace>
        </plugin>
    </gazebo>

</robot>